sphere_marker_node:
  ros__parameters:
    center_x: 0.7
    center_y: 0.1
    center_z: 0.55
    radius: 0.15
    color_r: 0.0
    color_g: 0.5
    color_b: 1.0
    color_a: 0.8
    frame_id: "world"
